language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "10"
  - "12"

env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4

install:
  - yarn
  - yarn remove webpack
  - yarn add webpack@$WEBPACK_VERSION

script:
  - yarn build

