language: node_js

cache:
  yarn: true

node_js:
  - "6"
# Not supported by yarn, or some other deeper deps (e.g. webpack -> terser-webpack-plugin)
#  - "7"
  - "8"
  - "9"
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
