language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "6"
# Not supported by yarn, or some other deeper deps (e.g. webpack -> terser-webpack-plugin)
#  - "7"
  - "8"
  - "9"
  - "10"

env:
  - WEBPACK_VERSION=3
  - WEBPACK_VERSION=4

install:
  - yarn
  - yarn remove webpack
  - yarn add webpack@$WEBPACK_VERSION

script:
  - yarn build

